---
title: "00-testing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install packages 
```{r}
require(tidyverse)
```

## Here I explore the genome feature files provided by the Tang et al. 2020 group 

Import genome feature file .gff
```{r}
gff <- read.delim(file = "../references/EVM.out_new.gff3", sep = "", header = F) %>% 
  separate(V1,sep = "_", into = c("a","b","scaffold_n"))
```

# 
```{r}
# Histo showing frequency of features listed on scaffold 1-104 
gff %>% 
  mutate(scaffold_n=as.numeric(scaffold_n)) %>% filter(scaffold_n<105) %>% 
  pull(scaffold_n) %>% hist(breaks=100)

# 271,164 features located on scaffold1-104 
a <- gff %>% 
  mutate(scaffold_n=as.numeric(scaffold_n)) %>% filter(scaffold_n<105) %>% 
  nrow()
paste("Number of features located on scaffolds 1-104:", prettyNum(a,big.mark = ","))

# How many unique scaffolds <105?
gff %>% 
  mutate(scaffold_n=as.numeric(scaffold_n)) %>% filter(scaffold_n<105) %>% 
  pull(scaffold_n) %>% unique() %>% sort() %>% length()

# Histo showing frequency of features listed on scaffolds 105-6958
gff %>% 
  mutate(scaffold_n=as.numeric(scaffold_n)) %>% filter(scaffold_n>104) %>% 
  pull(scaffold_n) %>% hist(breaks=100)

# 3,974 features located on scaffolds 105-6958
b <- gff %>% 
  mutate(scaffold_n=as.numeric(scaffold_n)) %>% filter(scaffold_n>104) %>% 
  nrow()
paste("Number of features located on scaffolds 104-6958:", prettyNum(b,big.mark = ","))

# How many unique scaffolds >104?
gff %>% 
  mutate(scaffold_n=as.numeric(scaffold_n)) %>% filter(scaffold_n>104) %>% 
  pull(scaffold_n) %>% unique() %>% sort() %>% length()
```


```{r}
(fasta.lengths <- read.delim(file = "../references/P.platypus_lengths_tab.txt", sep = "", header = F, col.names = c("scaffold", "length")) %>% 
  separate(scaffold,sep = "_", into = c("a","b","scaffold_n"), remove = F) %>% select(scaffold, length, scaffold_n) %>% 
  mutate(scaffold_n=as.numeric(scaffold_n)))

fasta.lengths %>% filter(scaffold_n<=104) %>% pull(length) %>% summary() 
fasta.lengths %>% filter(scaffold_n>104) %>% pull(length) %>% summary()


plot(x=log(fasta.lengths$scaffold_n), y=log(fasta.lengths$length), xlab = "log(scaffold number)", ylab="log(scaffold length)")

```

